package com.hero.ataa.ui.navigation

sealed class Screen(val route: String) {
    object LoginScreen : Screen("/login_screen")
    object RegisterScreen : Screen("/register_screen")
    object HomeScreen : Screen("/home_screen")
    object ProjectsScreen : Screen("/projects_screen")
    object ProjectScreen : Screen("/project_screen")
    object VolunteerOuterScreen : Screen("/volunteer_outer_screen")
    object LanguageScreen : Screen("/language_screen")
    object SadakaProjectScreen : Screen("/sadaka_project_screen")
    object MiskeenProjectScreen : Screen("/miskeen_project_screen")
    object SacrificeProjectScreen : Screen("/sacrifice_project_screen")
    object SettingsScreen : Screen("/settings_screen")
    object VerificationScreen : Screen("/verification_screen")
    object ProfileScreen : Screen("/profile_screen")
    object EditProfileScreen : Screen("/edit_profile_screen")
    object ReceiptsScreen : Screen("/receipts_screen")
    object ZakatProjectScreen : Screen("/zakat_screen")
    object PaymentScreen : Screen("/payment_screen")
    object EditNameScreen : Screen("/edit_name_screen")
    object EditPasswordScreen : Screen("/edit_password_screen")
    object SearchScreen : Screen("/search_screen")
    object BeneficiaryScreen : Screen("/beneficiary_screen")
    object BeneficiaryScreenOne : Screen("/beneficiary_screen/one")
    object BeneficiaryScreenTwo : Screen("/beneficiary_screen/two")
    object BeneficiaryScreenThree : Screen("/beneficiary_screen/three")
    object VolunteerScreen : Screen("/volunteer_screen")
    object VolunteerScreenOne : Screen("/volunteer_screen/one")
    object VolunteerScreenTwo : Screen("/volunteer_screen/two")
    object VolunteerScreenThree : Screen("/volunteer_screen/three")
}